# Generated by Django 5.2.1 on 2025-12-22 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_userprofile_logo_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='service_type',
            field=models.CharField(choices=[('Builders', 'Builders'), ('Interior Designers', 'Interior Designers'), ('Architects', 'Architects'), ('Electric Solutions', 'Electric Solutions'), ('Bathware Suppliers', 'Bathware Suppliers'), ('Furniture Retailers', 'Furniture Retailers'), ('Garden Solutions', 'Garden Solutions'), ('Fabrications', 'Fabrications'), ('Others', 'Others')], max_length=100),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='demo.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.user')),
            ],
            options={
                'unique_together': {('profile', 'user')},
            },
        ),
    ]
